### ISSUE TITLE
'Hordeum_vulgare' in below part shoud be 'hordeum_vulgare'

### ISSUE THREAD

**Issue by lilei1** [MorrellLAB/BAD_Mutations#25]
$ ./BAD_Mutations.py -v DEBUG \
                     setup \
                     -b /scratch/BAD_Mutations_Data \
                     -d /scratch/BAD_Mutations_Deps \
                     -t 'Hordeum_vulgare' \
                     -e 0.05 \
                     -m 10 \
                     -c BAD_Mutations_Config.txt 2> Setup.log

Maybe it is better give a hint that run "python /home/morrellp/llei/BAD_Mutations/BAD_Mutations.py -v DEBUG setup --list-species" to list the species.

**Comment by TomJKono** [comment]
Fixed in e4fa5bcbdd7ba8bfe87410d1dbb904ddee59188d, also added `--list-species` to examples.
