### ISSUE TITLE
create  new directories

### ISSUE THREAD

**Issue by lilei1** [MorrellLAB/BAD_Mutations#26]
I would like to say create new directories: mkdir -p /scratch/BAD_Mutations_Data /scratch/BAD_Mutations_Deps before run the below command line.
./BAD_Mutations.py -v DEBUG \
                     setup \
                     -b /scratch/BAD_Mutations_Data \
                     -d /scratch/BAD_Mutations_Deps \
                     -t 'Hordeum_vulgare' \
                     -e 0.05 \
                     -m 10 \
                     -c BAD_Mutations_Config.txt 2> Setup.log

**Comment by TomJKono** [comment]
Added `mkdir` to the example command line section
