### ISSUE TITLE
Warnning: Install pasta need specific DendroPy-3.12.3

### ISSUE THREAD

**Issue by lilei1** [MorrellLAB/BAD_Mutations#28]
When install pasta need to install specific DendroPy-3.12.3:
Install dendropy for pasta on MSI:
wget https://github.com/jeetsukumaran/DendroPy/archive/v3.12.3.tar.gz
tar -xvzf v3.12.2.tar.gz
cd DendroPy-3.12.3
python setup.py build -b $(pwd -P)
python setup.py install --user

**Comment by TomJKono** [comment]
This covered in the [PASTA manual](https://github.com/smirarab/pasta/blob/master/README.md). Will add a reference to the BAD_Mutations manual.
