### ISSUE TITLE
The fields in header of  the prediction output file inconsistent with the ones with NOSNP

### ISSUE THREAD

**Issue by lilei1** [MorrellLAB/BAD_Mutations#31]
When I extracted the items without NOSNP from the prediction output file, I saw the fields of the header (11) is inconsistent with the content fields (18). The first seven fields are repeating twice after the reference AA. I show the first 10 lines in the file, please see below:

Position	L0	L1	Constraint	Chisquared	P-value	SeqCount	Alignment	ReferenceAA	MaskedConstraint	MaskedP-value
417	-114.2504769550768	-109.8429675226595	2.600003815922569	8.815018864834457	0.002987611217884822	37	PEFSSC-FLCTTCCCPTP--SAAHASWWFFFFCCCCHQC--L	NA	417	-114.2504769550768	-109.8429675226595	2.600003815922569	8.815018864834457	0.002987611217884822	37	2.600003815922569	0.002987611217884822
432	-96.00793409068631	-95.98883661710803	0.901551054244307	0.03819494715654059	0.8450522026700051	34	AFFFFF-FFFFFTAVW-----FFLLLLLLLLLLLLLLSH--L	NA	432	-96.00793409068631	-95.98883661710803	0.901551054244307	0.03819494715654059	0.8450522026700051	34	0.901551054244307	0.8450522026700051
660	-70.25261880236872	-42.59972200094571	0.01476124340506724	55.30579360284601	1.03139718987677e-13	40	VVVVVVVVVVVVVVVVVVVVVVVVVIIIIIIIIIIIVVV--V	NA	660	-70.25261880236872	-42.59972200094571	0.01476124340506724	55.30579360284601	1.03139718987677e-13	40	0.01476124340506724	1.03139718987677e-13
933	-17.73616225941901	-17.18405710624295	2.423459124324687	1.104210306352108	0.293343971335091	10	--------------------------VVVVVKVVVV------	NA	933	-17.73616225941901	-17.18405710624295	2.423459124324687	1.104210306352108	0.293343971335091	10	2.423459124324687	0.293343971335091
1011	-76.5375368627051	-65.83106099341637	0.148075067122228	21.41295173857745	3.702615600342796e-06	35	SG-GGGG-GGGGGGGAAAAAS--S-SSSSSSSSSSSGGG--G	NA	1011	-76.5375368627051	-65.83106099341637	0.148075067122228	21.41295173857745	3.702615600342796e-06	35	0.148075067122228	3.702615600342796e-06
1128	-88.81552901538274	-88.65171196789275	0.7129923137686337	0.3276340949799703	0.5670555509255972	38	NN-NNNNNNNQQSEQEEEEEESIG-NNNNNNNNNNNQQE--E	NA	1128	-88.81552901538274	-88.65171196789275	0.7129923137686337	0.3276340949799703	0.5670555509255972	38	0.7129923137686337	0.5670555509255972
1134	-73.24644758771406	-66.2098928055336	0.222896653989791	14.07310956436092	0.0001758398293251195	37	TT-TTTTTNTTT-TIHPPPPPPPN-RSSSSSSSSSSTTT--A	NA	1134	-73.24644758771406	-66.2098928055336	0.222896653989791	14.07310956436092	0.0001758398293251195	37	0.222896653989791	0.0001758398293251195
1182	-61.99178040725806	-47.72236360077187	0.06212813833168374	28.53883361297238	9.183793447942179e-08	36	LL-LLLL-ILLL-LLLLLLLLLLL-IIIIIIIIIIILLL--I	NA	1182	-61.99178040725806	-47.72236360077187	0.06212813833168374	28.53883361297238	9.183793447942179e-08	36	0.06212813833168374	9.183793447942179e-08
1233	-72.04357072402931	-44.08226769565381	9.866446284317615e-17	55.92260605675099	7.538414337204813e-14	38	SSSSSSS-SSSSSSSSSSSSSSSS-SSSSSSSSSSSSSS--S	NA	1233	-72.04357072402931	-44.08226769565381	9.866446284317615e-17	55.92260605675099	7.538414337204813e-14	38	9.866446284317615e-17	7.538414337204813e-14

**Comment by TomJKono** [comment]
Fixed in 916ba9eaffe8276824b94c1930d5910237dfadc8
