### ISSUE TITLE
Fetch XML ParseError

### ISSUE THREAD

**Issue by mmckibben** [MorrellLAB/BAD_Mutations#47]
I am relatively new to the game, as such please pardon if there is an obvious answer to this I am missing. When attempting the Fetch command, I repeatedly run into the following error:

> Traceback (most recent call last):
  File "./BAD_Mutations.py", line 382, in <module>
    main()
  File "./BAD_Mutations.py", line 348, in main
    fetch(arguments_valid, loglevel)
  File "./BAD_Mutations.py", line 110, in fetch
    phy.get_xml_urls()
  File "/home/michaelmckibben/BAD_Mutations/lrt_predict/Fetch/phytozome.py", line 168, in get_xml_urls
    xml_tree = ElementTree.fromstring(xml)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: syntax error: line 1, column 49<

I have attempted  reinstalling all dependencies/Bad_Mutations, along with looking for similar issues related to xml around the internet to no avail. As such I decided to reach out here. Please let me know if there is a known solution to this problem. Thank you.

**Comment by TomJKono** [comment]
Hello,

Thank you for reaching out! It looks like Phytozome may be returning a different page than we expect. Can you rerun `BAD_Mutations` with the `-v DEBUG` option and paste the XML that is being served to you? Thank you!

**Comment by mmckibben** [comment]
Thank you for the quick reply! 

> ===2019-10-22 15:58:12,017 - Configuration_Handler===
> DEBUG	Setting variable BASE to /scratch/BAD_Mutations_Data
> ===2019-10-22 15:58:12,017 - Configuration_Handler===
> DEBUG	Setting variable TARGET_SPECIES to hordeum_vulgare
> ===2019-10-22 15:58:12,017 - Configuration_Handler===
> DEBUG	Setting variable EVAL_THRESHOLD to 0.05
> ===2019-10-22 15:58:12,017 - Configuration_Handler===
> DEBUG	Setting variable BASH to /bin/bash
> ===2019-10-22 15:58:12,017 - Configuration_Handler===
> DEBUG	Setting variable GZIP to /bin/gzip
> ===2019-10-22 15:58:12,017 - Configuration_Handler===
> DEBUG	Setting variable SUM to /usr/bin/sum
> ===2019-10-22 15:58:12,017 - Configuration_Handler===
> DEBUG	Setting variable TBLASTX to /usr/bin/tblastx
> ===2019-10-22 15:58:12,017 - Configuration_Handler===
> DEBUG	Setting variable PASTA to /usr/local/bin/run_pasta.py
> ===2019-10-22 15:58:12,017 - Configuration_Handler===
> DEBUG	Setting variable HYPHY to /usr/bin/hyphymp
> ===2019-10-22 15:58:12,017 - Configuration_Handler===
> DEBUG	Command line and config options merged. Values: {'sum_path': '/usr/bin/sum', 'target': 'hordeum_vulgare', 'gzip_path': '/bin/gzip', 'loglevel': 'DEBUG', 'config': 'BAD_Mutations_Config.txt', 'evalue': '0.05', 'fetch_only': False, 'action': 'fetch', 'base': '/scratch/BAD_Mutations_Data', 'user': ************, 'hyphy_path': '/usr/bin/hyphymp', 'convert_only': False, 'password': '**************, 'tblastx_path': '/usr/bin/tblastx', 'bash_path': '/bin/bash', 'pasta_path': '/usr/local/bin/run_pasta.py'}
> ===2019-10-22 15:58:12,017 - LRT_Predict===
> DEBUG	Checking if BAD_Mutations_Config.txt exists.
> ===2019-10-22 15:58:12,020 - LRT_Predict===
> DEBUG	fetch subcommand was invoked
> ===2019-10-22 15:58:12,022 - LRT_Predict===
> DEBUG	Creating a new Phytozome instance to fetch data.
> ===2019-10-22 15:58:12,022 - lrt_predict.Fetch.fetch===
> DEBUG	Creating new instance of Fetcher
> ===2019-10-22 15:58:12,022 - lrt_predict.Fetch.fetch===
> DEBUG	Base directory is /scratch/BAD_Mutations_Data
> ===2019-10-22 15:58:12,022 - lrt_predict.Fetch.fetch===
> DEBUG	Creating new instance of Phytozome
> ===2019-10-22 15:58:12,022 - lrt_predict.Fetch.fetch===
> DEBUG	Logging in to JGI Genomes Portal with username  ***********
> ===2019-10-22 15:58:12,023 - lrt_predict.Fetch.fetch===
> DEBUG	Cookies file: /tmp/BAD_Mutations_JGI_Cookie_lDWA0x.txt
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100   174    0   107  100    67    402    251 --:--:-- --:--:-- --:--:--   654
> ===2019-10-22 15:58:12,298 - LRT_Predict===
> DEBUG	Creating a new Ensembl instance to fetch data.
> ===2019-10-22 15:58:12,298 - lrt_predict.Fetch.fetch===
> DEBUG	Creating new instance of Fetcher
> ===2019-10-22 15:58:12,298 - lrt_predict.Fetch.fetch===
> DEBUG	Creating new instance of Fetcher
> ===2019-10-22 15:58:12,298 - lrt_predict.Fetch.fetch===
> DEBUG	Base directory is /scratch/BAD_Mutations_Data
> ===2019-10-22 15:58:12,298 - lrt_predict.Fetch.fetch===
> DEBUG	Base directory is /scratch/BAD_Mutations_Data
> ===2019-10-22 15:58:12,298 - lrt_predict.Fetch.fetch===
> DEBUG	Creating new instance of EnsemblPlants
> ===2019-10-22 15:58:12,298 - lrt_predict.Fetch.fetch===
> DEBUG	Creating new instance of EnsemblPlants
> ===2019-10-22 15:58:13,300 - LRT_Predict===
> DEBUG	Downloading and converting Ensembl Plants files...
> ===2019-10-22 15:58:13,976 - lrt_predict.Fetch.fetch===
> DEBUG	Attempting to cd into /pub/plants/current/fasta/aegilops_tauschii/cds/
> ===2019-10-22 15:58:13,976 - lrt_predict.Fetch.fetch===
> DEBUG	Attempting to cd into /pub/plants/current/fasta/aegilops_tauschii/cds/
> ===2019-10-22 15:58:15,029 - lrt_predict.Fetch.fetch===
> DEBUG	Appending /pub/release-45/plants/fasta/aegilops_tauschii/cds/Aegilops_tauschii.Aet_v4.0.cds.all.fa.gz onto list of files to fetch.
> ===2019-10-22 15:58:15,029 - lrt_predict.Fetch.fetch===
> DEBUG	Appending /pub/release-45/plants/fasta/aegilops_tauschii/cds/Aegilops_tauschii.Aet_v4.0.cds.all.fa.gz onto list of files to fetch.
> ===2019-10-22 15:58:15,873 - lrt_predict.Fetch.fetch===
> DEBUG	Attempting to cd into /pub/plants/current/fasta/brassica_oleracea/cds/
> ===2019-10-22 15:58:15,873 - lrt_predict.Fetch.fetch===
> DEBUG	Attempting to cd into /pub/plants/current/fasta/brassica_oleracea/cds/
> ===2019-10-22 15:58:17,562 - lrt_predict.Fetch.fetch===
> DEBUG	Appending /pub/release-45/plants/fasta/brassica_oleracea/cds/Brassica_oleracea.BOL.cds.all.fa.gz onto list of files to fetch.
> ===2019-10-22 15:58:17,562 - lrt_predict.Fetch.fetch===
> DEBUG	Appending /pub/release-45/plants/fasta/brassica_oleracea/cds/Brassica_oleracea.BOL.cds.all.fa.gz onto list of files to fetch.
> ===2019-10-22 15:58:18,376 - lrt_predict.Fetch.fetch===
> DEBUG	Attempting to cd into /pub/plants/current/fasta/hordeum_vulgare/cds/
> ===2019-10-22 15:58:18,376 - lrt_predict.Fetch.fetch===
> DEBUG	Attempting to cd into /pub/plants/current/fasta/hordeum_vulgare/cds/
> ===2019-10-22 15:58:20,059 - lrt_predict.Fetch.fetch===
> DEBUG	Appending /pub/release-45/plants/fasta/hordeum_vulgare/cds/Hordeum_vulgare.IBSC_v2.cds.all.fa.gz onto list of files to fetch.
> ===2019-10-22 15:58:20,059 - lrt_predict.Fetch.fetch===
> DEBUG	Appending /pub/release-45/plants/fasta/hordeum_vulgare/cds/Hordeum_vulgare.IBSC_v2.cds.all.fa.gz onto list of files to fetch.
> ===2019-10-22 15:58:20,194 - lrt_predict.Fetch.fetch===
> DEBUG	Attempting to cd into /pub/plants/current/fasta/leersia_perrieri/cds/
> ===2019-10-22 15:58:20,194 - lrt_predict.Fetch.fetch===
> DEBUG	Attempting to cd into /pub/plants/current/fasta/leersia_perrieri/cds/
> ===2019-10-22 15:58:22,336 - lrt_predict.Fetch.fetch===
> DEBUG	Appending /pub/release-45/plants/fasta/leersia_perrieri/cds/Leersia_perrieri.Lperr_V1.4.cds.all.fa.gz onto list of files to fetch.
> ===2019-10-22 15:58:22,336 - lrt_predict.Fetch.fetch===
> DEBUG	Appending /pub/release-45/plants/fasta/leersia_perrieri/cds/Leersia_perrieri.Lperr_V1.4.cds.all.fa.gz onto list of files to fetch.
> ===2019-10-22 15:58:22,470 - lrt_predict.Fetch.fetch===
> DEBUG	Attempting to cd into /pub/plants/current/fasta/musa_acuminata/cds/
> ===2019-10-22 15:58:22,470 - lrt_predict.Fetch.fetch===
> DEBUG	Attempting to cd into /pub/plants/current/fasta/musa_acuminata/cds/
> ===2019-10-22 15:58:24,741 - lrt_predict.Fetch.fetch===
> DEBUG	Appending /pub/release-45/plants/fasta/musa_acuminata/cds/Musa_acuminata.ASM31385v1.cds.all.fa.gz onto list of files to fetch.
> ===2019-10-22 15:58:24,741 - lrt_predict.Fetch.fetch===
> DEBUG	Appending /pub/release-45/plants/fasta/musa_acuminata/cds/Musa_acuminata.ASM31385v1.cds.all.fa.gz onto list of files to fetch.
> ===2019-10-22 15:58:24,876 - lrt_predict.Fetch.fetch===
> DEBUG	Attempting to cd into /pub/plants/current/fasta/triticum_urartu/cds/
> ===2019-10-22 15:58:24,876 - lrt_predict.Fetch.fetch===
> DEBUG	Attempting to cd into /pub/plants/current/fasta/triticum_urartu/cds/
> ===2019-10-22 15:58:26,544 - lrt_predict.Fetch.fetch===
> DEBUG	Appending /pub/release-45/plants/fasta/triticum_urartu/cds/Triticum_urartu.ASM34745v1.cds.all.fa.gz onto list of files to fetch.
> ===2019-10-22 15:58:26,544 - lrt_predict.Fetch.fetch===
> DEBUG	Appending /pub/release-45/plants/fasta/triticum_urartu/cds/Triticum_urartu.ASM34745v1.cds.all.fa.gz onto list of files to fetch.
> ===2019-10-22 15:58:26,679 - lrt_predict.Fetch.fetch===
> DEBUG	Species directory is /scratch/BAD_Mutations_Data/Aegilops_tauschii
> ===2019-10-22 15:58:26,679 - lrt_predict.Fetch.fetch===
> DEBUG	Species directory is /scratch/BAD_Mutations_Data/Aegilops_tauschii
> ===2019-10-22 15:58:26,682 - lrt_predict.Fetch.fetch===
> DEBUG	Checking if Aegilops_tauschii.Aet_v4.0.cds.all.fa.gz exists.
> ===2019-10-22 15:58:26,682 - lrt_predict.Fetch.fetch===
> DEBUG	Checking if Aegilops_tauschii.Aet_v4.0.cds.all.fa.gz exists.
> ===2019-10-22 15:58:26,682 - lrt_predict.Fetch.fetch===
> INFO	Calculating CRC32 on Aegilops_tauschii.Aet_v4.0.cds.all.fa.gz with  `sum' command.
> ===2019-10-22 15:58:26,682 - lrt_predict.Fetch.fetch===
> INFO	Calculating CRC32 on Aegilops_tauschii.Aet_v4.0.cds.all.fa.gz with  `sum' command.
> ===2019-10-22 15:58:26,765 - lrt_predict.Fetch.fetch===
> DEBUG	stdout:
> 17563 34350
> 
> ===2019-10-22 15:58:26,765 - lrt_predict.Fetch.fetch===
> DEBUG	stdout:
> 17563 34350
> 
> ===2019-10-22 15:58:26,766 - lrt_predict.Fetch.fetch===
> DEBUG	stderr:
> 
> ===2019-10-22 15:58:26,766 - lrt_predict.Fetch.fetch===
> DEBUG	stderr:
> 
> ===2019-10-22 15:58:26,766 - lrt_predict.Fetch.fetch===
> INFO	Comparing local checksum of 17563 and remote checksum of 17563
> ===2019-10-22 15:58:26,766 - lrt_predict.Fetch.fetch===
> INFO	Comparing local checksum of 17563 and remote checksum of 17563
> ===2019-10-22 15:58:26,766 - lrt_predict.Fetch.fetch===
> INFO	Aegilops_tauschii.Aet_v4.0.cds.all.fa.gz already exists and is current, skipping.
> ===2019-10-22 15:58:26,766 - lrt_predict.Fetch.fetch===
> INFO	Aegilops_tauschii.Aet_v4.0.cds.all.fa.gz already exists and is current, skipping.
> ===2019-10-22 15:58:26,766 - lrt_predict.Fetch.fetch===
> DEBUG	Species directory is /scratch/BAD_Mutations_Data/Brassica_oleracea
> ===2019-10-22 15:58:26,766 - lrt_predict.Fetch.fetch===
> DEBUG	Species directory is /scratch/BAD_Mutations_Data/Brassica_oleracea
> ===2019-10-22 15:58:26,766 - lrt_predict.Fetch.fetch===
> DEBUG	Checking if Brassica_oleracea.BOL.cds.all.fa.gz exists.
> ===2019-10-22 15:58:26,766 - lrt_predict.Fetch.fetch===
> DEBUG	Checking if Brassica_oleracea.BOL.cds.all.fa.gz exists.
> ===2019-10-22 15:58:26,766 - lrt_predict.Fetch.fetch===
> INFO	Calculating CRC32 on Brassica_oleracea.BOL.cds.all.fa.gz with  `sum' command.
> ===2019-10-22 15:58:26,766 - lrt_predict.Fetch.fetch===
> INFO	Calculating CRC32 on Brassica_oleracea.BOL.cds.all.fa.gz with  `sum' command.
> ===2019-10-22 15:58:26,818 - lrt_predict.Fetch.fetch===
> DEBUG	stdout:
> 39403 21548
> 
> ===2019-10-22 15:58:26,818 - lrt_predict.Fetch.fetch===
> DEBUG	stdout:
> 39403 21548
> 
> ===2019-10-22 15:58:26,818 - lrt_predict.Fetch.fetch===
> DEBUG	stderr:
> 
> ===2019-10-22 15:58:26,818 - lrt_predict.Fetch.fetch===
> DEBUG	stderr:
> 
> ===2019-10-22 15:58:26,818 - lrt_predict.Fetch.fetch===
> INFO	Comparing local checksum of 39403 and remote checksum of 39403
> ===2019-10-22 15:58:26,818 - lrt_predict.Fetch.fetch===
> INFO	Comparing local checksum of 39403 and remote checksum of 39403
> ===2019-10-22 15:58:26,818 - lrt_predict.Fetch.fetch===
> INFO	Brassica_oleracea.BOL.cds.all.fa.gz already exists and is current, skipping.
> ===2019-10-22 15:58:26,818 - lrt_predict.Fetch.fetch===
> INFO	Brassica_oleracea.BOL.cds.all.fa.gz already exists and is current, skipping.
> ===2019-10-22 15:58:26,818 - lrt_predict.Fetch.fetch===
> DEBUG	Species directory is /scratch/BAD_Mutations_Data/Hordeum_vulgare
> ===2019-10-22 15:58:26,818 - lrt_predict.Fetch.fetch===
> DEBUG	Species directory is /scratch/BAD_Mutations_Data/Hordeum_vulgare
> ===2019-10-22 15:58:26,818 - lrt_predict.Fetch.fetch===
> DEBUG	Checking if Hordeum_vulgare.IBSC_v2.cds.all.fa.gz exists.
> ===2019-10-22 15:58:26,818 - lrt_predict.Fetch.fetch===
> DEBUG	Checking if Hordeum_vulgare.IBSC_v2.cds.all.fa.gz exists.
> ===2019-10-22 15:58:26,818 - lrt_predict.Fetch.fetch===
> INFO	Calculating CRC32 on Hordeum_vulgare.IBSC_v2.cds.all.fa.gz with  `sum' command.
> ===2019-10-22 15:58:26,818 - lrt_predict.Fetch.fetch===
> INFO	Calculating CRC32 on Hordeum_vulgare.IBSC_v2.cds.all.fa.gz with  `sum' command.
> ===2019-10-22 15:58:26,887 - lrt_predict.Fetch.fetch===
> DEBUG	stdout:
> 14776 30336
> 
> ===2019-10-22 15:58:26,887 - lrt_predict.Fetch.fetch===
> DEBUG	stdout:
> 14776 30336
> 
> ===2019-10-22 15:58:26,888 - lrt_predict.Fetch.fetch===
> DEBUG	stderr:
> 
> ===2019-10-22 15:58:26,888 - lrt_predict.Fetch.fetch===
> DEBUG	stderr:
> 
> ===2019-10-22 15:58:26,888 - lrt_predict.Fetch.fetch===
> INFO	Comparing local checksum of 14776 and remote checksum of 14776
> ===2019-10-22 15:58:26,888 - lrt_predict.Fetch.fetch===
> INFO	Comparing local checksum of 14776 and remote checksum of 14776
> ===2019-10-22 15:58:26,888 - lrt_predict.Fetch.fetch===
> INFO	Hordeum_vulgare.IBSC_v2.cds.all.fa.gz already exists and is current, skipping.
> ===2019-10-22 15:58:26,888 - lrt_predict.Fetch.fetch===
> INFO	Hordeum_vulgare.IBSC_v2.cds.all.fa.gz already exists and is current, skipping.
> ===2019-10-22 15:58:26,888 - lrt_predict.Fetch.fetch===
> DEBUG	Species directory is /scratch/BAD_Mutations_Data/Leersia_perrieri
> ===2019-10-22 15:58:26,888 - lrt_predict.Fetch.fetch===
> DEBUG	Species directory is /scratch/BAD_Mutations_Data/Leersia_perrieri
> ===2019-10-22 15:58:26,888 - lrt_predict.Fetch.fetch===
> DEBUG	Checking if Leersia_perrieri.Lperr_V1.4.cds.all.fa.gz exists.
> ===2019-10-22 15:58:26,888 - lrt_predict.Fetch.fetch===
> DEBUG	Checking if Leersia_perrieri.Lperr_V1.4.cds.all.fa.gz exists.
> ===2019-10-22 15:58:26,888 - lrt_predict.Fetch.fetch===
> INFO	Calculating CRC32 on Leersia_perrieri.Lperr_V1.4.cds.all.fa.gz with  `sum' command.
> ===2019-10-22 15:58:26,888 - lrt_predict.Fetch.fetch===
> INFO	Calculating CRC32 on Leersia_perrieri.Lperr_V1.4.cds.all.fa.gz with  `sum' command.
> ===2019-10-22 15:58:26,925 - lrt_predict.Fetch.fetch===
> DEBUG	stdout:
> 05186 12866
> 
> ===2019-10-22 15:58:26,925 - lrt_predict.Fetch.fetch===
> DEBUG	stdout:
> 05186 12866
> 
> ===2019-10-22 15:58:26,925 - lrt_predict.Fetch.fetch===
> DEBUG	stderr:
> 
> ===2019-10-22 15:58:26,925 - lrt_predict.Fetch.fetch===
> DEBUG	stderr:
> 
> ===2019-10-22 15:58:26,925 - lrt_predict.Fetch.fetch===
> INFO	Comparing local checksum of 5186 and remote checksum of 5186
> ===2019-10-22 15:58:26,925 - lrt_predict.Fetch.fetch===
> INFO	Comparing local checksum of 5186 and remote checksum of 5186
> ===2019-10-22 15:58:26,925 - lrt_predict.Fetch.fetch===
> INFO	Leersia_perrieri.Lperr_V1.4.cds.all.fa.gz already exists and is current, skipping.
> ===2019-10-22 15:58:26,925 - lrt_predict.Fetch.fetch===
> INFO	Leersia_perrieri.Lperr_V1.4.cds.all.fa.gz already exists and is current, skipping.
> ===2019-10-22 15:58:26,925 - lrt_predict.Fetch.fetch===
> DEBUG	Species directory is /scratch/BAD_Mutations_Data/Musa_acuminata
> ===2019-10-22 15:58:26,925 - lrt_predict.Fetch.fetch===
> DEBUG	Species directory is /scratch/BAD_Mutations_Data/Musa_acuminata
> ===2019-10-22 15:58:26,925 - lrt_predict.Fetch.fetch===
> DEBUG	Checking if Musa_acuminata.ASM31385v1.cds.all.fa.gz exists.
> ===2019-10-22 15:58:26,925 - lrt_predict.Fetch.fetch===
> DEBUG	Checking if Musa_acuminata.ASM31385v1.cds.all.fa.gz exists.
> ===2019-10-22 15:58:26,925 - lrt_predict.Fetch.fetch===
> INFO	Calculating CRC32 on Musa_acuminata.ASM31385v1.cds.all.fa.gz with  `sum' command.
> ===2019-10-22 15:58:26,925 - lrt_predict.Fetch.fetch===
> INFO	Calculating CRC32 on Musa_acuminata.ASM31385v1.cds.all.fa.gz with  `sum' command.
> ===2019-10-22 15:58:26,965 - lrt_predict.Fetch.fetch===
> DEBUG	stdout:
> 13214 13510
> 
> ===2019-10-22 15:58:26,965 - lrt_predict.Fetch.fetch===
> DEBUG	stdout:
> 13214 13510
> 
> ===2019-10-22 15:58:26,965 - lrt_predict.Fetch.fetch===
> DEBUG	stderr:
> 
> ===2019-10-22 15:58:26,965 - lrt_predict.Fetch.fetch===
> DEBUG	stderr:
> 
> ===2019-10-22 15:58:26,965 - lrt_predict.Fetch.fetch===
> INFO	Comparing local checksum of 13214 and remote checksum of 13214
> ===2019-10-22 15:58:26,965 - lrt_predict.Fetch.fetch===
> INFO	Comparing local checksum of 13214 and remote checksum of 13214
> ===2019-10-22 15:58:26,965 - lrt_predict.Fetch.fetch===
> INFO	Musa_acuminata.ASM31385v1.cds.all.fa.gz already exists and is current, skipping.
> ===2019-10-22 15:58:26,965 - lrt_predict.Fetch.fetch===
> INFO	Musa_acuminata.ASM31385v1.cds.all.fa.gz already exists and is current, skipping.
> ===2019-10-22 15:58:26,965 - lrt_predict.Fetch.fetch===
> DEBUG	Species directory is /scratch/BAD_Mutations_Data/Triticum_urartu
> ===2019-10-22 15:58:26,965 - lrt_predict.Fetch.fetch===
> DEBUG	Species directory is /scratch/BAD_Mutations_Data/Triticum_urartu
> ===2019-10-22 15:58:26,965 - lrt_predict.Fetch.fetch===
> DEBUG	Checking if Triticum_urartu.ASM34745v1.cds.all.fa.gz exists.
> ===2019-10-22 15:58:26,965 - lrt_predict.Fetch.fetch===
> DEBUG	Checking if Triticum_urartu.ASM34745v1.cds.all.fa.gz exists.
> ===2019-10-22 15:58:26,965 - lrt_predict.Fetch.fetch===
> INFO	Calculating CRC32 on Triticum_urartu.ASM34745v1.cds.all.fa.gz with  `sum' command.
> ===2019-10-22 15:58:26,965 - lrt_predict.Fetch.fetch===
> INFO	Calculating CRC32 on Triticum_urartu.ASM34745v1.cds.all.fa.gz with  `sum' command.
> ===2019-10-22 15:58:27,001 - lrt_predict.Fetch.fetch===
> DEBUG	stdout:
> 35497 12606
> 
> ===2019-10-22 15:58:27,001 - lrt_predict.Fetch.fetch===
> DEBUG	stdout:
> 35497 12606
> 
> ===2019-10-22 15:58:27,002 - lrt_predict.Fetch.fetch===
> DEBUG	stderr:
> 
> ===2019-10-22 15:58:27,002 - lrt_predict.Fetch.fetch===
> DEBUG	stderr:
> 
> ===2019-10-22 15:58:27,002 - lrt_predict.Fetch.fetch===
> INFO	Comparing local checksum of 35497 and remote checksum of 35497
> ===2019-10-22 15:58:27,002 - lrt_predict.Fetch.fetch===
> INFO	Comparing local checksum of 35497 and remote checksum of 35497
> ===2019-10-22 15:58:27,002 - lrt_predict.Fetch.fetch===
> INFO	Triticum_urartu.ASM34745v1.cds.all.fa.gz already exists and is current, skipping.
> ===2019-10-22 15:58:27,002 - lrt_predict.Fetch.fetch===
> INFO	Triticum_urartu.ASM34745v1.cds.all.fa.gz already exists and is current, skipping.
> ===2019-10-22 15:58:27,002 - lrt_predict.Fetch.fetch===
> INFO	Done downloading CDS files from Ensembl.
> ===2019-10-22 15:58:27,002 - lrt_predict.Fetch.fetch===
> INFO	Done downloading CDS files from Ensembl.
> ===2019-10-22 15:58:27,136 - LRT_Predict===
> DEBUG	Downloading and converting files.
> ===2019-10-22 15:58:27,137 - lrt_predict.Fetch.fetch===
> DEBUG	Fetching XML
> ===2019-10-22 15:58:27,137 - lrt_predict.Fetch.fetch===
> DEBUG	Fetching XML
> ===2019-10-22 15:58:27,198 - lrt_predict.Fetch.fetch===
> DEBUG	The XML I got was 
> 
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>302 Found</title>
> </head><body>
> <h1>Found</h1>
> <p>The document has moved <a href="https://genome.jgi.doe.gov/ext-api/downloads/get-directory?organism=Phytozome">here</a>.</p>
> </body></html>
> 
> ===2019-10-22 15:58:27,198 - lrt_predict.Fetch.fetch===
> DEBUG	The XML I got was 
> 
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>302 Found</title>
> </head><body>
> <h1>Found</h1>
> <p>The document has moved <a href="https://genome.jgi.doe.gov/ext-api/downloads/get-directory?organism=Phytozome">here</a>.</p>
> </body></html>
> 
> Traceback (most recent call last):
>   File "./BAD_Mutations.py", line 382, in <module>
>     main()
>   File "./BAD_Mutations.py", line 348, in main
>     fetch(arguments_valid, loglevel)
>   File "./BAD_Mutations.py", line 110, in fetch
>     phy.get_xml_urls()
>   File "/home/michaelmckibben/BAD_Mutations/lrt_predict/Fetch/phytozome.py", line 168, in get_xml_urls
>     xml_tree = ElementTree.fromstring(xml)
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
>     parser.feed(text)
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
>     self._raiseerror(v)
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
>     raise err
> xml.etree.ElementTree.ParseError: syntax error: line 1, column 49

I assume it has something with the "has been move to here" portions, however I was not 100% sure. Let me know if you need more info, and thank you again for the assistance!

**Comment by TomJKono** [comment]
Hello,

Thank you for the debugging output. It looks like the Phytozome XML did change locations. This is updated in the `dev` branch: can you try to run `git checkout dev` from inside the BAD_Mutations directory and try again? I'll also note that the `dev` version has been updated for Python3 syntax, so you'll need that, too. I apologise for the trouble, and thank you!

**Comment by mmckibben** [comment]
Happy Monday. That seems to have worked, thank you again for your help!

**Comment by TomJKono** [comment]
Glad to hear it! I hope to have these fixes rolled into the master branch soon. Thank you!
